---
draft: true
title: defining alluvial diagrams
author: ~
date: 
slug: alluvial-vs-sankey
categories: [progress]
tags: [flow diagrams,sankey diagrams,alluvial diagrams,visualization]
---

```{r knitr options, echo=FALSE}
knitr::opts_chunk$set(
  message = FALSE,
  fig.height = 3, fig.width = 8
)
```

## Background

I first encountered alluvial diagrams, so-called, in a widely-shared 2010 [paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0008694) by Martin Rosvall and Carl T. Bergstrom. They were investigating the shifting boundaries between distinct scientific fields ("modules"), as reconstructed from sequential years of journal citation data ("states"), and proposed a specialized flow diagram "to highlight the significant changes, fusions, and fissions that the modules undergo between each pair of successive states". At the time, i was unfamiliar with Sankey diagrams and only passingly familiar with flow diagrams---mostly by way of my computational biologist colleagues and their literature-derived signal transduction networks---but i could imagine myriad uses for this alluvial genre and eventually went searching for an implementation in R.

This led me to the [alluvial](https://github.com/mbojan/alluvial) package, which Michał Bojanowski was actively developing. As i got more comfortable with and excited about the then-ascendant tidyverse, i took it upon myself to put together [a ggplot2 extension](https://github.com/corybrunson/ggalluvial), which has since become considerably widely used. I later learned that previous developers had released similar extensions, specifically "parallel sets plots" in Thomas Lin Pedersen's [ggforce](https://ggforce.data-imaginist.com) and in Heike Hofmann's [ggparallel](https://github.com/heike/ggparallel).[^ggpcp]
With continual exposure to these diverse implementations, i began to notice some subtle but important distinctions between others' and my design principles. It also became clear that there was no consensus distinction between _alluvial_ diagrams/plots and the much more well-established genres of _Sankey_ diagrams and _parallel sets_ plots---indeed, no consensus on whether a distinction existed! Based on [the ggalluvial issues page](https://github.com/corybrunson/ggalluvial/issues) and [an occasional query on Stack Overflow](https://stackoverflow.com/search?q=ggalluvial), the lack of generally accepted terms surrounding these sorts of diagrams remains a source of confusion.[^literature] My goal in this post is to propose some vocabulary and a taxonomy to ~~alluviate~~ alleviate this confusion, or at least serve as a point of reference for others to propose improvements!

[^ggpcp]: I only just discovered Yawei Ge and Heike Hofmann's [ggpcp](https://yaweige.github.io/ggpcp/) package for general parallel coordinate plots, under active development!
[^literature]: That's not to say that useful distinctions haven't been made somewhere, e.g. the technical literature on data visualization, but i feel confident in claiming that they have had limited effects on practice!

## A proposed taxonomy of width-encoded diagrams

Since the terms "diagram" and "plot" (along with "chart" and "graph") are sometimes used interchangeably and sometimes fiercely contested, i'll adopt a convention here and invite suggestions to improve it: **Diagrams** visualize data, and **plots** are diagrams that are uniquely determined by the data and a fixed set of plotting rules.[^layers]
In these terms, ggalluvial and the other R packages discussed here unambiguously produce _plots_.

[^layers]: In ggplot2, these rules are the stat, geom, coord, and scale layers. One of the great contributions of ggplot2, in my view, was to make them explicit to lay users like myself.

Here are how i think these various diagrams---flow, Sankey, parallel sets, and alluvial---are related:

1. _Flow diagrams encode directed flows._ Flow diagrams may use ribbons, arrows, or other graphical elements to represent flows---that is, directed processes. For example, directed network diagrams of resource transmission between nodes are flow diagrams. Note that flows are not necessarily between nodes: Many Sankey diagrams include incoming or outgoing arrows representing flows from or to elements outside the diagram.
2. _Sankey diagrams are flow diagrams with flow weights encoded as ribbon widths._ Flow diagrams may not be weighted: Signal transduction networks, for example, usually are not. While Sankey diagrams are extremely flexible, their defining characteristic is that weighted flows are represented by ribbons whose width indicates the weight or "volume" of flow through them.
3. [Parallel coordinates plots](https://datascience.blog.wzb.eu/2016/09/27/parallel-coordinate-plots-for-discrete-and-categorical-data-in-r-a-comparison/) depict cases in a data set by their coordinates along several continuous dimensions, i.e. their values at several continuous variables, arrayed along a discrete axis. _Parallel sets plots are analogous to parallel coordinates plots with discrete-valued classificatory dimensions in place of continuous-valued coordinate dimensions._ This imposes two requirements on the plotting rules: They must determine the order, and preserve the relative sizes, of the classes along each dimension. In practice, this means that ribbon widths indicate either the absolute weights of the cases or their proportions of the total weight.
4. _Alluvial plots are parallel sets plots in which classes are ordered consistently across dimensions and stacked (without gaps) at each dimension._ This yields a plot with a meaningful continuous axis perpendicular to the discrete axis: The height of a stack at any class is the cumulative weight of the preceding classes. (Alluvial plots also tend to use splines rather than straight segments to connect dimensions, though i think this is far less important than the differences in the plotting rules.)

### How my taxonomy stacks up

Without exhaustively surveying the Internet and technical literature, it's worthwhile to benchmark my distinctions against those made by some popular chart catalogues, which are much more representative of usage patterns. Xenographics lists several at the end of [their discussion of graphonyms](https://xeno.graphics/articles/on-graphonyms-the-importance-of-chart-type-names/), and of these three make clear distinctions between some of the types described above:

* [The DataViz Project](https://datavizproject.com/) describes Sankey diagrams as i did above, and distinguishes alluvial plots from parallel sets plots only in terms of the orientation of the axes (which is horizontal versus vertical) and of the shapes of the connecting ribbons.
* [The Data Visualization Catalogue](https://datavizcatalogue.com) distinguishes parallel sets plots from Sankey diagrams as not using arrows and binning the flows (ribbons) at regular intervals. (They don't have an entry on alluvial plots.)
* [The Visualization Universe](http://visualizationuniverse.com/charts/) has entries for Sankey diagrams and alluvial plots, but their descriptions are excerpts (or, at least, subsets) of those of the DataViz Project.

Importantly, in my taxonomy, **alluvial plots are not Sankey diagrams, nor even flow diagrams**. This seems appropriate on reflection, since even the original alluvial diagrams did not represent the transmission of material or information between nodes but changes in classification over time.[^flows] This is not to say that alluvial plots cannot represent flow data---several popular examples do---but that the plot elements are not _specific_ to flow data; and, as a result, the directedness of flow data may not be conveyed well in an alluvial plot.[^network] I seem to be in agreement with the popular catalogues here.[^rawgraphs]
I'll also endorse Elijah Meeks' point, [from this Medium post](https://medium.com/@Elijah_Meeks/alluvial-charts-and-their-discontents-10a77d55216b), that Sankey diagrams can include cycles, whereas parallel sets and alluvial plots would not be able to encode such relations.

[^network]: A similar misfit is a simplicial complex represented by a network diagram: The type of diagram is designed for a different type of data (pairwise-relational with possible directedness and multiplicity) and fails to convey essential data elements (higher-dimensional simplices).

[^flows]: It's unfortunate that i named the ribbons between adjacent axes _flows_ in ggalluvial, but i maintain that it was preferable to calling them _fans_.

[^rawgraphs]: A contrary example is RAWGraphs, which [describes alluvial plots](https://rawgraphs.io/learning/how-to-make-an-alluvial-diagram/) as "a specific kind of Sankey diagrams".

However, i'm also making a distinction between alluvial and parallel sets plots that the catalogues---and, in my experience, other developers---don't make.
Indeed, i haven't seen a discussion anywhere else of whether a parallel sets or alluvial plot puts repeated categories in the same order,[^order] or whether the parallel sets are stacked so that the perpendicular axis measures their cumulative size, or whether either of these features is relevant.
Having spent hours on the problem of whether different orderings might benefit a plot, and having been prompted several times to implement gaps between the sets, i've come to take the strong position that this distinction matters and that the terminology should reflect it.
While good definitions describe usage rather than prescribe it, i think it's worth making an argument for this particular technical distinction while the terminology has not yet hardened.

[^order]: In [this blog post](https://matthewdharris.com/2017/11/11/a-brief-diversion-into-static-alluvial-sankey-diagrams-in-r/), Matt Harris compared how several implementations sorted the sets, but did not discuss whether their order might vary.

## A prescription for distinguishing alluvial and parallel sets plots

### Caveat

Neither Rosvall and Bergstrom, who popularized alluvial diagrams, nor Bojanowski, on whose package i based ggalluvial, included a cumulative weight axis perpendicular to the dimensions axis. In fact, what originally prompted me to cut out the gaps between strata in ggalluvial was that i didn't know how to get rid of the vertical axis when rendering plots! Like every great idea i believe i've had, i was forced into this one.

### Gist

My argument has two steps. First, i claim that the features that distinguish alluvial from parallel sets plots, in my taxonomy, have practical importance.
...

* uses in scientific literature and blogs
* parallel sets plots are often interactive and give users the ability to reorder sets

That's really the entirety of my argument for the distinction; my second step is merely a finishing fluorish: To remark that these special features are connoted by the terminology of alluvial diagrams: I've decided to call the rectangles representing the parallel sets "strata" to suggest that they are more stable than the crisscrossing alluvia, and indeed this stability (with respect to their order in the plot) is what users expect when many of the categorical dimensions classify subjects into the same categories. The term also suggests, as does "alluvia", that the various sets into which the subjects are partitioned at each (usually horizontal) position along the dimension axis are themselves (vertically) positioned in accordance with gravity. That is, they have "settled", or been "deposited", one atop another with no defiant space in between.

## Coda

I am by no means an expert in data visualization! While i feel strongly that my taxonomy makes the best of the present scrambling of terms, i am quite open to countersuggestions and especially to use cases that undercut it. If you come across them, please do send them my way.
